### PR TITLE
PHP Macaroons upgrade

### PR DESCRIPTION
**Pull request by cmckni3**
- Updates libsodium
- Updates libsodium PHP bindings
- Updates php-macaroons

### CODE REVIEW

**Comment by cmckni3** [comment]
Not sure why cargo is spewing errors now :(

**Comment by ecordell** [comment]
Thanks for the updates Chris! I'll pull locally and see if I can figure out the cargo stuff. IIRC, rust wasn't at 1.0 when I wrote the Rust tests so things have probably changed.

**Comment by ecordell** [comment]
Build is broken in master anyway, so I'll go ahead and merge this and fix the build later. Thanks!

**Comment by cmckni3** [comment]
I'll figure out why the autoloader for PHP isn't working tonight if I have time.

**Pull request merged**
